#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.upgradecheck
Version  : 0.1.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/a2/96/fc882ff29ba1e2ba696b0466bea91d9218ba85748226b380a8d91ccde841/oslo.upgradecheck-0.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/a2/96/fc882ff29ba1e2ba696b0466bea91d9218ba85748226b380a8d91ccde841/oslo.upgradecheck-0.1.1.tar.gz
Summary  : Common code for writing OpenStack upgrade checks
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.upgradecheck-license = %{version}-%{release}
Requires: oslo.upgradecheck-python = %{version}-%{release}
Requires: oslo.upgradecheck-python3 = %{version}-%{release}
Requires: Babel
Requires: enum34
Requires: oslo.config
Requires: oslo.i18n
BuildRequires : buildreq-distutils3
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslosphinx
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : stestr
BuildRequires : tox
BuildRequires : virtualenv
Patch1: req.patch

%description
oslo.upgradecheck
        ===================================
        
        Common code for writing OpenStack upgrade checks
        
        This project contains the common code necessary for writing upgrade checks
        in OpenStack projects. It includes a module (oslo_upgradecheck.upgradecheck)
        for the common code as well as an example (oslo_upgradecheck.__main__) of
        integrating that code into a project.

%package license
Summary: license components for the oslo.upgradecheck package.
Group: Default

%description license
license components for the oslo.upgradecheck package.


%package python
Summary: python components for the oslo.upgradecheck package.
Group: Default
Requires: oslo.upgradecheck-python3 = %{version}-%{release}

%description python
python components for the oslo.upgradecheck package.


%package python3
Summary: python3 components for the oslo.upgradecheck package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.upgradecheck package.


%prep
%setup -q -n oslo.upgradecheck-0.1.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545578291
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.upgradecheck
cp LICENSE %{buildroot}/usr/share/package-licenses/oslo.upgradecheck/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.upgradecheck/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
