#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.upgradecheck
Version  : 0.2.1
Release  : 4
URL      : https://files.pythonhosted.org/packages/59/e3/ee2acc4b48d7520a5ce82d200a62a674217005df54e517ed9c1fdbec9d6f/oslo.upgradecheck-0.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/59/e3/ee2acc4b48d7520a5ce82d200a62a674217005df54e517ed9c1fdbec9d6f/oslo.upgradecheck-0.2.1.tar.gz
Summary  : Common code for writing OpenStack upgrade checks
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.upgradecheck-license = %{version}-%{release}
Requires: oslo.upgradecheck-python = %{version}-%{release}
Requires: oslo.upgradecheck-python3 = %{version}-%{release}
Requires: Babel
Requires: enum34
Requires: oslo.config
Requires: oslo.i18n
BuildRequires : Sphinx
BuildRequires : Sphinx-python
BuildRequires : buildreq-distutils3
BuildRequires : dulwich-python
BuildRequires : hacking
BuildRequires : openstackdocstheme-python
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslotest
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : reno-python
BuildRequires : stestr
BuildRequires : stestr-python
BuildRequires : tox
BuildRequires : virtualenv
Patch1: req.patch

%description
===================================
oslo.upgradecheck
===================================

%package license
Summary: license components for the oslo.upgradecheck package.
Group: Default

%description license
license components for the oslo.upgradecheck package.


%package python
Summary: python components for the oslo.upgradecheck package.
Group: Default
Requires: oslo.upgradecheck-python3 = %{version}-%{release}

%description python
python components for the oslo.upgradecheck package.


%package python3
Summary: python3 components for the oslo.upgradecheck package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.upgradecheck package.


%prep
%setup -q -n oslo.upgradecheck-0.2.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555948604
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.upgradecheck
cp LICENSE %{buildroot}/usr/share/package-licenses/oslo.upgradecheck/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.upgradecheck/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
